### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by thebigsmileXD** [soundreactor/scdl#6]
> https://mrvv.net/scdl/

gives me "invalid soundcloud link" for everything, so this extension won't download songs

**Comment by soundreactor** [comment]
its fixed now. 
https://addons.mozilla.org/en-US/firefox/addon/scdl-soundcloud-downloader/ <https://addons.mozilla.org/en-US/firefox/addon/scdl-soundcloud-downloader/>
