### ISSUE TITLE
Extension breaking soundcloud.com

### ISSUE THREAD

**Issue by git-eri** [soundreactor/scdl#8]
(Firefox) The extension prevents soundcloud.com from loading any tracks or data. Deactivating fixes it but makes the extension useless.

**Comment by T21yx64** [comment]
I'm having same issue

**Comment by SarahSzabo** [comment]
Yep, same issue:
Disabling SDCL -> Reenable SDCL worked for some reason though, but this shouldn't happen :D

**Comment by holysnipz** [comment]
console spammed with CORS errors:
 - `CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://soundcloud.com, *’` 
 - `Reason: CORS request did not succeed`
 
 mostly at `https://api-v2.soundcloud.com` requests

**Comment by T21yx64** [comment]
I have started using counterpart alternative

https://www.soundcloudmp3.org/

**Comment by GitHubRoy** [comment]
Anyone know of any alternative that also renders a download button next to each track

**Comment by soundreactor** [comment]
fixed. sorry for the delay
